app:
  name: matflow

APP_HOME: ${APP_HOME}

application: matflow

setting:
  address: tiklab-matflow-starter/src/main/resources/settings.xml

server:
  port: 8090

#jdbc:
#  driverClassName: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://172.10.1.10:3306/tiklab_matflow?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#  username: root
#  password: darth2020

jdbc:
  driverClassName: org.postgresql.Driver
#  url: jdbc:postgresql://172.10.1.10:5432/tiklab_matflow?currentSchema=tiklab_matflow&stringtype=unspecified
  url: jdbc:postgresql://172.10.1.10:5432/tiklab_matflow?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
PROJECT_HOME: ${user.home}/matflow/${app.name}
plugin:
  path: ${PROJECT_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${PROJECT_HOME}/caches

message:
  sms:
    enabled: true

eas:
  embbed:
    enable: true
#    enable: false
#  address: http://eas-ce.mastre.tiklab.net
#  web:
#    address: http://eas-ce.local.tiklab.net

base:
  url: http://192.168.10.5:3000

mysql:
  embbed:
    enable: false
  database: tiklab_matflow

#homes
homes:
  address: http://192.168.10.7:8080

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.dev.tiklab.net













