app:
  name: matflow

APP_HOME: ${APP_HOME}
application: matflow

server:
  port: 8080

jdbc:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://172.12.1.10:5432/tiklab_matflow?stringtype=unspecified
  username: postgres
  password: darth2020

#plugin config
PROJECT_HOME: ${user.home}/matflow/${app.name}
plugin:
  path: ${PROJECT_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: false
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${PROJECT_HOME}/caches

message:
  sms:
    enabled: true

eas:
  embbed:
    enable: false
  address: http://eas-ce.demo.tiklab.net

base:
  url: http://matflow-ce.demo.tiklab.net

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.demo.tiklab.net


#homes
homes:
  address: http://homes.demo.tiklab.net










