app:
  name: tiklab-matflow
spring:
  profiles:
    active: prd

APP_HOME: ${APP_HOME}
application: matFlow

server:
  port: 8090

jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/tiklab_matflow?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  username: root
  password: darth2020

#plugin config
PROJECT_HOME: ${user.home}/matflow/${app.name}

plugin:
  path: ${PROJECT_HOME}/plugin

#dfs config
dfs:
  server:
    enabled: true
    mode: server
    port: 4000
    datapath: ${PROJECT_HOME}/files
  client:
    url: 127.0.0.1:4000
    bucket: ${app.name}

#dcs config
dcs:
  server:
    enabled: false
    mode: server
    port: 5000
    datapath: ${PROJECT_HOME}/caches
  client:
    url: 127.0.0.1:5000
    bucket: ${app.name}

#dcs config
dss:
  server:
    enabled: false
    mode: server
    port: 6000
    datapath: ${PROJECT_HOME}/index
  client:
    url: 127.0.0.1:6000
    bucket: ${app.name}

datapath: ${PROJECT_HOME}/caches

#eas config
eas:
  embbed:
    enable: true
  server:
    port: 8080
  address: http://localhost:8080
  web:
    address: http://localhost:8080
  jdbc:
    driverClassName: ${jdbc.driverClassName}
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
mysql:
  embbed:
    enable: true
  server:
    port: 3306
  version: mysql-8.0.28
  name: tiklab_matflow

#homes
homes:
  address: http://172.19.6.134:8080

#license
licences:
  path: ${APP_HOME}/licences

#file
file:
  path: http://file.tiklab.net


git:
  gitee:
    client:
      id: 84e4a3626d037a717fb4952f09abdf2624ce28a0beffb92cb4eac67479e05b34
      secret: f38167d54948136b9ca4e4ca454573b3c3d485db575a91a0e784a04599a20054
    callback:
      url: http%3A%2F%2Ftiklab_pipeline%2F%23%2Findex%2Ftask%2Fconfig
  github:
    client:
      id: cf93e472f1ffe9521474
      secret: 6b39934dfbd13a5d92c888a50a0709526b9dd445
    callback:
      url: http://matFlow.tiklab.net/#/index/task/config















